### ISSUE TITLE
A default ingress should be created for `web*` processes.

### ISSUE THREAD

**Issue by ewdurbin** [cabotage/cabotage-app#118]
Cabotage creates a [default service](https://github.com/cabotage/cabotage-app/blob/a44a2d56f544691884a12a165352dcea11ece39d/cabotage/celery/tasks/deploy.py#L159-L216) for accessing `web*` and `tcp*` processes, but does not expose them via ingress.

We should probably create a default ingress for each `web*` process, or at least expose an option to.

A minimal ingress might look something like:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: 10s
    nginx.ingress.kubernetes.io/proxy-next-upstream: error
    nginx.ingress.kubernetes.io/proxy-read-timeout: 10s
    nginx.ingress.kubernetes.io/proxy-request-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-send-timeout: 10s
    nginx.ingress.kubernetes.io/service-upstream: "true"
  name: {release.application.project.slug}-{release.application.slug}-{process_name}
  namespace: {release.application.project.organization.slug}
spec:
  ingressClassName: nginx
  rules:
  - host: {release.application.project.organization.slug}-{release.application.project.slug}-{release.application.slug}-{process_name}.{INGRESS_DOMAIN}
    http:
      paths:
      - backend:
          service:
            name: {release.application.project.slug}-{release.application.slug}-{process_name}
            port:
              number: 8000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {release.application.project.organization.slug}-{release.application.project.slug}-{release.application.slug}-{process_name}.{INGRESS_DOMAIN}
    secretName: ingress-{release.application.project.organization.slug}-{release.application.project.slug}-{release.application.slug}-{process_name}
```

Where INGRESS_DOMAIN is a configuration value specific to a given cabotage installation.

This would allow for the most common pattern we have where deployments use cabotage ingress as a backend for CDN, but we could allow for configuration of additional hostnames for serving from ingress directly.
